title: Will Johnson
markdown: kramdown
url: ""
baseurl: "https://williamjohnson.dev"

# for atom feed
author:
  name: Will Johnson
  email: hey@williamjohnson.dev
  image: "https://avatars0.githubusercontent.com/u/40403549?s=460&u=0dd089a9c8a13b2e682277101fe6705978326cf7&v=4"
  bio: Ruby On Rails Developer Sharing What I Learn
  twitter: "willjohnsonio"

plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-twitter-plugin

defaults:
  - scope:
      path: ""
    values:
      layout: "post"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      permalink: /posts/:categories/:year/:month/:day/:title/
